"""Add payment_mode and voucher_id to SalarySlip

Revision ID: 4cd6a188ee4e
Revises: ccb81c878784
Create Date: 2026-06-23 01:40:24.405497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd6a188ee4e'
down_revision = 'ccb81c878784'
branch_labels = None
depends_on = None


def _column_exists(table_name, column_name):
    """Check if a column already exists in a table."""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT FROM information_schema.columns WHERE table_name = :t AND column_name = :c)"
    ), {'t': table_name, 'c': column_name})
    return result.scalar()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('salary_slips', 'payment_mode'):
        op.add_column('salary_slips', sa.Column('payment_mode', sa.String(length=20), nullable=True))
    if not _column_exists('salary_slips', 'voucher_id'):
        op.add_column('salary_slips', sa.Column('voucher_id', sa.Integer(), nullable=True))

    try:
        with op.batch_alter_table('salary_slips', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_salary_slips_voucher_id', 'vouchers', ['voucher_id'], ['id'])
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_slips', schema=None) as batch_op:
        batch_op.drop_constraint('fk_salary_slips_voucher_id', type_='foreignkey')
        batch_op.drop_column('voucher_id')
        batch_op.drop_column('payment_mode')

    # ### end Alembic commands ###
