"""Add HRMS models

Revision ID: 6ce3740e5b94
Revises: be400ed2ed95
Create Date: 2026-06-22 20:21:09.180801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce3740e5b94'
down_revision = 'be400ed2ed95'
branch_labels = None
depends_on = None


def _table_exists(table_name):
    """Check if a table already exists in the database (handles db.create_all() state)."""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = :t)"
    ), {'t': table_name})
    return result.scalar()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: All create_table calls are guarded with _table_exists() because
    # these tables may have been previously created by db.create_all() in
    # start.sh before Alembic's version tracker was synced.

    if not _table_exists('account_groups'):
        op.create_table('account_groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('nature', sa.String(length=50), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['account_groups.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )

    if not _table_exists('customers'):
        op.create_table('customers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('gst_number', sa.String(length=20), nullable=True),
        sa.Column('state', sa.String(length=50), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('employees'):
        op.create_table('employees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('designation', sa.String(length=100), nullable=True),
        sa.Column('department', sa.String(length=100), nullable=True),
        sa.Column('base_salary', sa.Float(), nullable=True),
        sa.Column('joined_at', sa.Date(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('employee_code')
        )

    if not _table_exists('expenses'):
        op.create_table('expenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('payment_mode', sa.String(length=20), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('ledger_entries'):
        op.create_table('ledger_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('debit', sa.Float(), nullable=True),
        sa.Column('credit', sa.Float(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('reference_type', sa.String(length=50), nullable=True),
        sa.Column('reference_id', sa.Integer(), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('products'):
        op.create_table('products',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('selling_price', sa.Float(), nullable=True),
        sa.Column('purchase_cost', sa.Float(), nullable=True),
        sa.Column('stock_quantity', sa.Float(), nullable=True),
        sa.Column('low_stock_threshold', sa.Float(), nullable=True),
        sa.Column('gst_rate', sa.Float(), nullable=True),
        sa.Column('hsn_code', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )

    if not _table_exists('suppliers'):
        op.create_table('suppliers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('gst_number', sa.String(length=20), nullable=True),
        sa.Column('state', sa.String(length=50), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('users'):
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
        )

    if not _table_exists('attendance'):
        op.create_table('attendance',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('inventory_transactions'):
        op.create_table('inventory_transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('transaction_type', sa.String(length=50), nullable=False),
        sa.Column('reference_id', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('ledgers'):
        op.create_table('ledgers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('opening_balance', sa.Float(), nullable=True),
        sa.Column('opening_balance_type', sa.String(length=2), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )

    if not _table_exists('production_runs'):
        op.create_table('production_runs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('finished_product_id', sa.Integer(), nullable=False),
        sa.Column('quantity_produced', sa.Float(), nullable=False),
        sa.Column('logged_by', sa.Integer(), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['finished_product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('purchases'):
        op.create_table('purchases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('supplier_id', sa.Integer(), nullable=False),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.Column('paid_amount', sa.Float(), nullable=True),
        sa.Column('balance_amount', sa.Float(), nullable=True),
        sa.Column('total_cgst', sa.Float(), nullable=True),
        sa.Column('total_sgst', sa.Float(), nullable=True),
        sa.Column('total_igst', sa.Float(), nullable=True),
        sa.Column('payment_mode', sa.String(length=20), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('salary_slips'):
        op.create_table('salary_slips',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('month', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('basic_salary', sa.Float(), nullable=True),
        sa.Column('allowances', sa.Float(), nullable=True),
        sa.Column('deductions', sa.Float(), nullable=True),
        sa.Column('net_salary', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('generated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('sales'):
        op.create_table('sales',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.Column('paid_amount', sa.Float(), nullable=True),
        sa.Column('balance_amount', sa.Float(), nullable=True),
        sa.Column('total_cgst', sa.Float(), nullable=True),
        sa.Column('total_sgst', sa.Float(), nullable=True),
        sa.Column('total_igst', sa.Float(), nullable=True),
        sa.Column('discount_percentage', sa.Float(), nullable=True),
        sa.Column('discount_amount', sa.Float(), nullable=True),
        sa.Column('payment_mode', sa.String(length=20), nullable=True),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('vouchers'):
        op.create_table('vouchers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('voucher_type', sa.String(length=50), nullable=False),
        sa.Column('voucher_number', sa.String(length=50), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('narration', sa.Text(), nullable=True),
        sa.Column('reference', sa.String(length=100), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('voucher_number')
        )

    if not _table_exists('production_consumptions'):
        op.create_table('production_consumptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('production_run_id', sa.Integer(), nullable=False),
        sa.Column('raw_material_id', sa.Integer(), nullable=False),
        sa.Column('quantity_consumed', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['production_run_id'], ['production_runs.id'], ),
        sa.ForeignKeyConstraint(['raw_material_id'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('purchase_items'):
        op.create_table('purchase_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('purchase_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('unit_cost', sa.Float(), nullable=False),
        sa.Column('subtotal', sa.Float(), nullable=False),
        sa.Column('cgst_amount', sa.Float(), nullable=True),
        sa.Column('sgst_amount', sa.Float(), nullable=True),
        sa.Column('igst_amount', sa.Float(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('sale_items'):
        op.create_table('sale_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sale_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('unit_price', sa.Float(), nullable=False),
        sa.Column('unit_cost', sa.Float(), nullable=True),
        sa.Column('subtotal', sa.Float(), nullable=False),
        sa.Column('cgst_amount', sa.Float(), nullable=True),
        sa.Column('sgst_amount', sa.Float(), nullable=True),
        sa.Column('igst_amount', sa.Float(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('voucher_entries'):
        op.create_table('voucher_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('voucher_id', sa.Integer(), nullable=False),
        sa.Column('ledger_id', sa.Integer(), nullable=False),
        sa.Column('entry_type', sa.String(length=2), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
        sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voucher_entries')
    op.drop_table('sale_items')
    op.drop_table('purchase_items')
    op.drop_table('production_consumptions')
    op.drop_table('vouchers')
    op.drop_table('sales')
    op.drop_table('salary_slips')
    op.drop_table('purchases')
    op.drop_table('production_runs')
    op.drop_table('ledgers')
    op.drop_table('inventory_transactions')
    op.drop_table('attendance')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('products')
    op.drop_table('ledger_entries')
    op.drop_table('expenses')
    op.drop_table('employees')
    op.drop_table('customers')
    op.drop_table('account_groups')
    # ### end Alembic commands ###
