"""Enterprise HRMS Update

Revision ID: ccb81c878784
Revises: 6ce3740e5b94
Create Date: 2026-06-22 20:34:07.271704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb81c878784'
down_revision = '6ce3740e5b94'
branch_labels = None
depends_on = None


def _table_exists(table_name):
    """Check if a table already exists in the database."""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = :t)"
    ), {'t': table_name})
    return result.scalar()


def _column_exists(table_name, column_name):
    """Check if a column already exists in a table."""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT FROM information_schema.columns WHERE table_name = :t AND column_name = :c)"
    ), {'t': table_name, 'c': column_name})
    return result.scalar()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('factories'):
        op.create_table('factories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('attendance_radius', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )

    if not _table_exists('hr_audit_logs'):
        op.create_table('hr_audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=True),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('hr_notifications'):
        op.create_table('hr_notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('leave_requests'):
        op.create_table('leave_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('leave_type', sa.String(length=50), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('days', sa.Float(), nullable=True),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.Column('applied_at', sa.DateTime(), nullable=True),
        sa.Column('actioned_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    # Safely add columns to attendance (skip if already exist)
    attendance_cols = {
        'factory_id': sa.Integer(), 'check_in': sa.DateTime(), 'check_out': sa.DateTime(),
        'working_hours': sa.Float(), 'overtime_hours': sa.Float(),
        'checkin_latitude': sa.Float(), 'checkin_longitude': sa.Float(),
        'location_verified': sa.Boolean(), 'device_info': sa.String(length=255)
    }
    for col_name, col_type in attendance_cols.items():
        if not _column_exists('attendance', col_name):
            op.add_column('attendance', sa.Column(col_name, col_type, nullable=True))

    try:
        with op.batch_alter_table('attendance', schema=None) as batch_op:
            batch_op.alter_column('status', existing_type=sa.VARCHAR(length=20), nullable=True)
            batch_op.create_foreign_key('fk_attendance_factory', 'factories', ['factory_id'], ['id'])
    except Exception:
        pass  # FK or alter may already exist

    # Safely add columns to employees
    employee_cols = {
        'photo_filename': sa.String(length=255), 'address': sa.Text(),
        'employment_type': sa.String(length=50), 'factory_id': sa.Integer(),
        'user_id': sa.Integer(), 'casual_leave_balance': sa.Float(),
        'sick_leave_balance': sa.Float(), 'emergency_leave_balance': sa.Float()
    }
    for col_name, col_type in employee_cols.items():
        if not _column_exists('employees', col_name):
            op.add_column('employees', sa.Column(col_name, col_type, nullable=True))

    try:
        with op.batch_alter_table('employees', schema=None) as batch_op:
            batch_op.create_unique_constraint('uq_employees_user', ['user_id'])
            batch_op.create_foreign_key('fk_employees_factory', 'factories', ['factory_id'], ['id'])
            batch_op.create_foreign_key('fk_employees_user', 'users', ['user_id'], ['id'])
    except Exception:
        pass  # Constraints may already exist

    # Safely add columns to salary_slips
    salary_cols = {
        'working_days': sa.Integer(), 'days_present': sa.Integer(),
        'days_absent': sa.Integer(), 'total_overtime_hours': sa.Float(),
        'overtime_pay': sa.Float(), 'bonus': sa.Float()
    }
    for col_name, col_type in salary_cols.items():
        if not _column_exists('salary_slips', col_name):
            op.add_column('salary_slips', sa.Column(col_name, col_type, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_slips', schema=None) as batch_op:
        batch_op.drop_column('bonus')
        batch_op.drop_column('overtime_pay')
        batch_op.drop_column('total_overtime_hours')
        batch_op.drop_column('days_absent')
        batch_op.drop_column('days_present')
        batch_op.drop_column('working_days')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employees_user', type_='foreignkey')
        batch_op.drop_constraint('fk_employees_factory', type_='foreignkey')
        batch_op.drop_constraint('uq_employees_user', type_='unique')
        batch_op.drop_column('emergency_leave_balance')
        batch_op.drop_column('sick_leave_balance')
        batch_op.drop_column('casual_leave_balance')
        batch_op.drop_column('user_id')
        batch_op.drop_column('factory_id')
        batch_op.drop_column('employment_type')
        batch_op.drop_column('address')
        batch_op.drop_column('photo_filename')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendance_factory', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('device_info')
        batch_op.drop_column('location_verified')
        batch_op.drop_column('checkin_longitude')
        batch_op.drop_column('checkin_latitude')
        batch_op.drop_column('overtime_hours')
        batch_op.drop_column('working_hours')
        batch_op.drop_column('check_out')
        batch_op.drop_column('check_in')
        batch_op.drop_column('factory_id')

    op.drop_table('leave_requests')
    op.drop_table('hr_notifications')
    op.drop_table('hr_audit_logs')
    op.drop_table('factories')
    # ### end Alembic commands ###
